### ISSUE TITLE
Meta archive download error

### ISSUE THREAD

**Issue by gavinmdouglas** [CCB-SB/plsdb#13]
Hi there,

I'm running into issues downloading the meta archive (version 2021_06_23).

I've tried multiple browsers, computers, and ip addresses, but in each case the download reaches 1.01GB/1.2GB and then fails with only the message "Connection closed at byte 1085348400".

Any idea what could be going on here? I was able to download the FASTA archive no problem.

Thanks,

Gavin

**Comment by SmalJonni** [comment]
Hi Gavin,
We are looking into the problem. After some testing, we were able to confirm the issue. While we are working on a fix please download the archive from [here](https://figshare.com/articles/dataset/PLSDB_2021_06_23/17049395) 
Regards,
Georges

**Comment by gavinmdouglas** [comment]
Great thanks @SmalJonni

**Comment by SmalJonni** [comment]
Adjustments were made to the webserver and we hope that this issue has now been fixed.

**Comment by gavinmdouglas** [comment]
Yes it seems to download fine now!
