### ISSUE TITLE
Include archaeal plasmids

### ISSUE THREAD

**Issue by apcamargo** [CCB-SB/plsdb#14]
PLSDB currently hosts only bacterial plasmids. WOuld it be within the project's scope to also add plasmids of Archaea?

**Comment by Xethic** [comment]
Hi,
we are currently reviewing this option and keep you in the loop via this thread.

Best

**Comment by SDmetagenomics** [comment]
Yes we would very much like to see this implemented. I have done a rudimentary version using the same search string you guys used slightly modified:

biomol_genomic[PROP] AND plasmid[filter] NOT complete cds[Title] NOT gene[Title] NOT genes[Title] NOT contig[Title] NOT scaffold[Title] NOT whole genome map[Title] NOT partial sequence[Title] NOT partial plasmid[Title] NOT locus[Title] NOT region[Title] NOT fragment[Title] NOT integron[Title] NOT transposon[Title] NOT insertion sequence[Title] NOT insertion element[Title] NOT phage[Title] NOT operon[Title] AND archaea[filter]

Made non-redundant by mash clustering with dist = 0 

Seems like this would be an excellent addition to the next update!

**Comment by G-Molano-LA** [comment]
From the version 2024_05_31, now PLSDB also includes Archaeal plasmids.
