### ISSUE TITLE
README.md for PLSDB v. 2021_06_23

### ISSUE THREAD

**Issue by haruosuz** [CCB-SB/plsdb#15]
https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/download/
> A README file is also provided explaining the content and formatting of all included files.

Where can I download the README file?

The META archive and FASTA archive were downloaded on 2022-02-02 using:
```
wget https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/download/plasmids_meta.tar.bz2
tar -jxvf plasmids_meta.tar.bz2
wget https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/download/plsdb.fna.bz2
bunzip2 -c plsdb.fna.bz2 > plsdb.fna
```

**Comment by VGalata** [comment]
I can confirm that the `README` file is missing in the "meta" archive.

@SmalJonni It seems that this files was forgotten. Maybe in the future the `README` could be also included in this repository to track changes and to provide a copy of the description of the data?

**Comment by SmalJonni** [comment]
Thank you for reporting the issue.

-  The README file was added to the meta archive.
-  A bug in the main .tsv file was fixed addressing 3 columns. Please download the newest version of the database.

I will think about a solution that automatically includes the README.md of the meta archive in the README.md of this repository, so the file only has to be updated once. Accordingly, I will leave the issue open for now.

**Comment by haruosuz** [comment]
pMCBF1 (AY950444) is not included in PLSDB v. 2021_06_23_v2.
> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3104523/
> pMCBF1 formed a novel clade, hereafter called ζ.
> Sequences of pMCBF1 and pMCBF6 were deposited in GenBank; Nucleotide Core #(accession AY950444 and EF107516).

**Comment by SmalJonni** [comment]
Thank you for reporting the issue.
We can confirm that the plasmid is not included. The plasmid is not picked up during data collection due to an incorrect organism specification. 
We are currently looking into possible solutions.
