### ISSUE TITLE
updating the plsdb for 2022?

### ISSUE THREAD

**Issue by intikhab** [CCB-SB/plsdb#18]
Dear plsdb team,

Your work is impressive, especially in collecting the metadata related to plasmids. I wish to scan the data with a few interesting plasmid genes, I can see the results for data up to 2020. Do you have a recent release from 2022? This will help to understand the presence of genes of interest in the most updated dataset. 

Do you plan to update your db from the latest dataset of NCBI?

Looking forward to your response,

Best Wishes,
Intikhab Alam
CBRC, KAUST

**Comment by SmalJonni** [comment]
Hi,
We thank you for your interest in our work.

We had a data update scheduled for May. However, due to various difficulties with the pipeline, we had to reschedule it and we hope to be able to provide the update by the end of July.

Regards.
