### ISSUE TITLE
API/website not working

### ISSUE THREAD

**Issue by gbouras13** [CCB-SB/plsdb#19]
Hi,

When I use the website to try and search a sequence, I am getting an error:

Ooops!!! 500
Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

Likewise when I try the API, I get an error:

raise Exception("Returned response: " + data['label'] + ' Please check again your input file and the input specifications as well as the chosen search_type.')
Exception: Returned response: error Please check again your input file and the input specifications as well as the chosen search_type.

George

**Comment by SmalJonni** [comment]
Hello,
Thank you for drawing this to our attention.
We were able to confirm this issue and it should be fixed by now. Please feel free to comment in case this problem persists.
Regards
