### ISSUE TITLE
Web search tool not working

### ISSUE THREAD

**Issue by jgoff91** [CCB-SB/plsdb#20]
I keep getting the following error when trying to submit any search on the website: 

Ooops!!! 500
Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

I have confirmed the search tool does not work with the example files provided on the site. 

v.2021_06_23_v2

**Comment by SmalJonni** [comment]
Hello,
Thanks for notifying us of the issue. This appears to be the same issue as #19 and we applied the same _temporary_ fix. Since this issue seems to reoccur we will be working on a permanent solution for the issue. In the meantime, in case the problem reoccurs please notify us in #19.
Regards
