### ISSUE TITLE
Plasmid detected, but which contig?

### ISSUE THREAD

**Issue by Kata-Pa** [CCB-SB/plsdb#21]
Hello,

thank you for the tool, it is really one of the few that detects both circular and linear plasmids. Maybe I am missing the information, but is it somewhere mentioned which contig corresponds to the plasmid detected? If not, are there any plans to add this information?

Thank you!

**Comment by Kata-Pa** [comment]
I am sorry, I forgot to mention that I am referring to the online tool.

**Comment by VGalata** [comment]
Hi @Kata-Pa,

Happy to hear that you like the tool. :)

If you are referring to the results from `mash screen`then there is no information about which FASTA sequences match a plasmid from the database. `mash screen` only tells you whether a plasmid is represented in your data. Other search options should provide matches. i.e. a mapping from the input FASTA sequences to plasmids.

Edit: for `mash dist`, the results are only provided per input sequence if the option for processing each of them individually is enabled.
