### ISSUE TITLE
Resistance genes information

### ISSUE THREAD

**Issue by mdiricks** [CCB-SB/plsdb#23]
Dear PLSDB team,
Where can you find information on the resistance genes found on the plasmids? And with which thresholds are these genes evaluated (gene coverage and identity).
Kind regards,

**Comment by mdiricks** [comment]
Found it:
You need to click on the plasmid in the overview table to get into the specific plasmid overview. Resistance genes are then mentioned (only if found) in the Additional annotations section (see e.g. https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/plasmid/NC_017908.2/).

Tresholds are unclear though.

**Comment by VGalata** [comment]
Hi @mdiricks,

We use [abricate](https://github.com/tseemann/abricate) for resistance annotations and the thresholds can be found [here in the workflow config](https://github.com/VGalata/plsdb/blob/master/config/config.json#L76).

Best wishes,
Valentina
