### ISSUE TITLE
problem to use website

### ISSUE THREAD

**Issue by Fla1487** [CCB-SB/plsdb#24]
When I use the website to try and search a sequence, I am getting an error:

Ooops!!! 500
Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

Could I know if ther is a temporary errors due to server update? thank you for yu great work.

**Comment by Xethic** [comment]
Hi @Fla1487 

it seems you hit one of the maintenance slots.
Can you please try again and confirm whether it works on your side?

Thanks!

**Comment by Fla1487** [comment]
Now it works.

Thank you so much

Flavio De Maio PhD
Istituto di Microbiologia e Virologia
Microbiota analysis & Microbial WGS Research Core Facilty, GSTeP
Fondazione Policlinico Universitario A. Gemelli IRCCS
L.go Agostino Gemelli, 8
00168 Roma (Italy)

Da: Fabian ***@***.***>
Inviato: martedì 7 febbraio 2023 13:55
A: ***@***.***>
Cc: De Maio ***@***.***>; ***@***.***>
Oggetto: Re: [VGalata/plsdb] problem to use website (Issue #24)


Hi @Fla1487<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFla1487&data=05%7C01%7Cflavio.demaio%40unicatt.it%7C629d2998ea854186447d08db090a8dfa%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C638113713180847346%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LJU8JAcmZWw%2FfeA6y8GQskzTSXCFXiPToB4RYbVlyKc%3D&reserved=0>

it seems you hit one of the maintenance slots.
Can you please try again and confirms whether it works on your side?

Thanks!

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVGalata%2Fplsdb%2Fissues%2F24%23issuecomment-1420725686&data=05%7C01%7Cflavio.demaio%40unicatt.it%7C629d2998ea854186447d08db090a8dfa%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C638113713180847346%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A4kIoRHwaxI5HyjqzY1Os7gShJVj0ZIaMrWrUdaE4VM%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANDJXTDN7CGLXRCVAVMEHY3WWJA2NANCNFSM6AAAAAAUQW2QD4&data=05%7C01%7Cflavio.demaio%40unicatt.it%7C629d2998ea854186447d08db090a8dfa%7Cb94f7d7481ff44a9b5886682acc85779%7C0%7C0%7C638113713180847346%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HbmZCGvfa7HIiN%2F4bCFwAJVgfe2d%2Bi%2B63MSvbIKJpHM%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>


[http://static.unicatt.it/ext-portale/5xmille%20firma%20mail%202022.jpg]
