### ISSUE TITLE
PLSDB webpage doesn't work

### ISSUE THREAD

**Issue by marketanykrynova** [CCB-SB/plsdb#26]
Hello,

The ccb-microbe.cs.uni-saarland.de/plsdb/ page is currently displaying a "You don't have permission to access this resource" error. Any insights on when it will be back up?

Thanks.

**Comment by G-Molano-LA** [comment]
Hi!

Sorry you experience that. The webpage was available but incorrectly redirected sometimes. Now you should not encounter any problems.

Bests,

Alejandra
