### ISSUE TITLE
I would like to know if the .fna files of plasmids downloaded from the PSDB website are all contigs?

### ISSUE THREAD

**Issue by ZoeLct** [CCB-SB/plsdb#28]
Hello, I am a beginner in the field of bioinformatics. I would like to know if the .fna files of plasmids downloaded from the PSDB website are all contigs?
If possible, I would like to ask how to distinguish between reads and contigs in FASTA format? I always have trouble determining whether the downloaded FASTA files are reads or contigs.
Thank you for your help.

**Comment by G-Molano-LA** [comment]
Hi,

PLSDB sequences are completed sequences, so no reads/contigs are in the FASTA files.
