### ISSUE TITLE
Where to download the Plasmid fasta file？

### ISSUE THREAD

**Issue by Winjor** [CCB-SB/plsdb#3]
Hi, where to download the plasmid fasta file？I downloaded the ZIP archive form https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/download/， but not found the fasta file. I want to use the fasta to build a bwa index for bwa align. Thanks.

**Comment by VGalata** [comment]
Dear @Winjor,

The FASTA file can be extracted from the BLAST database included in the download:
```bash
blastdbcmd -entry all -db <database label> -out <outfile>
```

I will include this information into the README file in the next update.
