### ISSUE TITLE
Download Fasta sequences

### ISSUE THREAD

**Issue by ayabrown** [CCB-SB/plsdb#7]
Hi, 
Thanks for this wonderful collection of plasmids DNA. 
I would like to use the collection as a bowtie index and not a blast db, its there a way to download just the Fasta seqs of the plasmids? 

Thanks in advance. 

Aya

**Comment by VGalata** [comment]
Dear @ayabrown,

You can extract the FASTA sequences from the BLAST database which is included in the download.

Assuming that you have downloaded and decompressed the PLSDB archive, and BLAST is installed:

```bash
# extract seqs from blastdb
blastdbcmd -entry all -db "plsdb.fna" -out "plsdb.fasta"
``` 

Let me know if you have more questions.

Best,
Valentina

**Comment by ayabrown** [comment]
Worked beautifully, Thanks!
